connect_debug_port u_ila_0/probe2 [get_nets [list design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/mb/flag_int_to_cpu]]
connect_debug_port u_ila_0/probe3 [get_nets [list design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/mb/flag_int_to_nyuzi]]
set_property PACKAGE_PIN A17 [get_ports {red_led[3]}]
set_property PACKAGE_PIN G2 [get_ports {red_led[2]}]
set_property PACKAGE_PIN Y21 [get_ports {red_led[1]}]
set_property PACKAGE_PIN W21 [get_ports {red_led[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports {red_led[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports {red_led[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {red_led[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {red_led[0]}]
set_property PACKAGE_PIN K15 [get_ports ext_reset_in]
set_property IOSTANDARD LVCMOS15 [get_ports ext_reset_in]

create_debug_core u_ila_0_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0_0]
set_property C_DATA_DEPTH 65536 [get_debug_cores u_ila_0_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0_0]
set_property port_width 1 [get_debug_ports u_ila_0_0/clk]
connect_debug_port u_ila_0_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0_0/probe0]
connect_debug_port u_ila_0_0/probe0 [get_nets [list {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[0]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[1]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[2]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[3]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[4]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[5]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[6]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[7]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[8]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[9]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[10]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[11]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[12]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[13]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[14]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[15]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[16]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[17]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[18]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[19]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[20]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[21]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[22]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[23]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[24]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[25]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[26]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[27]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[28]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[29]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[30]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/slv_reg0[31]}]]
create_debug_port u_ila_0_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0_0/probe1]
set_property port_width 3 [get_debug_ports u_ila_0_0/probe1]
connect_debug_port u_ila_0_0/probe1 [get_nets [list {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/mb/state_cur[0]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/mb/state_cur[1]} {design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/mb/state_cur[2]}]]
create_debug_port u_ila_0_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe2]
connect_debug_port u_ila_0_0/probe2 [get_nets [list design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/mb/int_to_cpu]]
create_debug_port u_ila_0_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe3]
connect_debug_port u_ila_0_0/probe3 [get_nets [list design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/mb/int_to_nyuzi]]
create_debug_port u_ila_0_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe4]
connect_debug_port u_ila_0_0/probe4 [get_nets [list design_1_i/mailbox_v1_0_0/inst/mailbox_v1_0_S00_AXI_inst/mb/io_from_nyuzi]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
