webtalk_init -webtalk_dir G:\\xilinx_project\\zynq_nyuzi_0111\\nyuzi\\nyuzi.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "星期五 一月 13 15:45:19 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "30g1ola5pr22sq2eqeivu7hbu9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_20" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "20" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1484280307350" -context "sdk\\\\application/1484280307350"
webtalk_add_data -client sdk -key os -value "linux" -context "sdk\\\\application/1484280307350"
webtalk_add_data -client sdk -key apptemplate -value "linux_hello_world" -context "sdk\\\\application/1484280307350"
webtalk_add_data -client sdk -key uid -value "1484280676526" -context "sdk\\\\bsp/1484280676526"
webtalk_add_data -client sdk -key hwid -value "1484121512268" -context "sdk\\\\bsp/1484280676526"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1484280676526"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1484280676526"
webtalk_add_data -client sdk -key uid -value "1484280686308" -context "sdk\\\\application/1484280686308"
webtalk_add_data -client sdk -key hwid -value "1484121512268" -context "sdk\\\\application/1484280686308"
webtalk_add_data -client sdk -key bspid -value "1484280676526" -context "sdk\\\\application/1484280686308"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1484280686308"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1484280686308"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1484280686308"
webtalk_transmit -clientid 618180403 -regid "" -xml G:\\xilinx_project\\zynq_nyuzi_0111\\nyuzi\\nyuzi.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html G:\\xilinx_project\\zynq_nyuzi_0111\\nyuzi\\nyuzi.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm G:\\xilinx_project\\zynq_nyuzi_0111\\nyuzi\\nyuzi.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
